name: Build Book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Build all formats
        run: |
          docker run --rm -v ${{ github.workspace }}:/book iksnae/book-builder:latest
      
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: book-pdf
          path: build/*.pdf
          
      - name: Upload EPUB artifact
        uses: actions/upload-artifact@v3
        with:
          name: book-epub
          path: build/*.epub
          
      - name: Upload MOBI artifact
        uses: actions/upload-artifact@v3
        with:
          name: book-mobi
          path: build/*.mobi
          
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: book-html
          path: build/*.html
      
      - name: Create GitHub Release (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.pdf
            build/*.epub
            build/*.mobi
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}